# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a Node.js base image
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY src /app/src

# Build the project
RUN npm run build

# Use a minimal Node.js image for the production build
FROM node:20-alpine AS production

# Set working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build /app/build

# Copy necessary config files
COPY package.json package-lock.json /app/

# Set environment variable for SwitchBot token
ENV SWITCHBOT_TOKEN=your_token

# Run the server
CMD ["node", "build/index.js"]